version: "3.9"
services:
  app:
    build: ./
    environment:
      RABBITMQ_SERVER: "host.docker.internal"
      STATISTIC_SERVER: "host.docker.internal:8282"
      DB_SERVER: mssql
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
      OTEL_SERVICE_NAME: "store"
      OTEL_EXPORTER_OTLP_ENDPOINT: ""
      OTEL_LOGS_EXPORTER: "otlp"
    ports:
      - "8581:8581"
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    expose:
      - "1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!23
      - MSSQL_PID=Developer
  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password!23" -Q "create database Data"; do sleep 5; done'

volumes:
  sqlserver_data:


