version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-util
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
    networks:
      - rabbitmq_net
    volumes:
      - rabbitmq_data:/data

networks:
  rabbitmq_net:
    name: rabbitmq-net
    
volumes:
  rabbitmq_data:
