version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!23
      - MSSQL_PID=Developer
  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password!23" -Q "create database Data"; do sleep 5; done'

networks:
  sqlserver_net:
    name: sqlserver-net

volumes:
  sqlserver_data: