version: "3.9"
services:
  app:
    build: ./
    environment:
      RABBITMQ_SERVER: "host.docker.internal"
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
      OTEL_SERVICE_NAME: "statistic"
      OTEL_EXPORTER_OTLP_ENDPOINT: ""
      OTEL_LOGS_EXPORTER: "otlp"
    ports:
      - "8282:8282"
    expose:
      - "8282"