INSERT INTO game VALUES ('1', 'Warframe', 'Digital Extremes', 'Action');
INSERT INTO game VALUES ('2', 'Dark Souls 3', 'FromSoftware, Inc.', 'Action');
INSERT INTO game VALUES ('3', 'Red Redemption', 'Rockstar Games', 'Action, Adventure');
INSERT INTO game VALUES ('4', 'Raft', 'Redbeet Interactive', 'Adventure');
INSERT INTO game VALUES ('5', 'Fishing Planet', 'Fishing Planet LLC', 'Simulation, Sports');
INSERT INTO game VALUES ('6', 'CS:GO', 'Valve, Hidden Path Entertainment', 'Action');
INSERT INTO game VALUES ('7', 'League of Legends', 'Riot Games', 'MOBA');
INSERT INTO game VALUES ('8', 'Yu-Gi-Oh! Duel Links', 'Konami Digital Entertainment', 'Strategy');
INSERT INTO game VALUES ('9', 'New World', 'Amazon Games', 'RPG, Action');
INSERT INTO game VALUES ('10', 'Golf it', 'Perfuse Entertainment', 'Sports');
INSERT INTO game VALUES ('11', 'Valorant', 'Riot Games', 'FPS');
INSERT INTO game VALUES ('12', 'Hearstone', 'Blizzard', 'Strategy');
INSERT INTO game VALUES ('13', 'Dota 2', 'Valve', 'MOBA');
INSERT INTO game VALUES ('14', 'Minecraft', 'Mojang Studios, Telltale Games, Xbox Game Studios, 4J Studios, Other Ocean Interactive, Double Eleven', '14-10-1959 10:10:10');
INSERT INTO game VALUES ('15', 'The Isle', 'Afterthought LLC', 'Action, Simulation, Adventure');
INSERT INTO game VALUES ('16', 'Sea of Thieves', 'Rare Ltd', 'Action, Adventure');
INSERT INTO game VALUES ('17', 'Jump Force', 'Spike Chunsoft Co., Ltd.','Action');
INSERT INTO game VALUES ('18', 'Among US', 'Innersloth', ' Casual');
INSERT INTO game VALUES ('19', 'Runeterra', 'Riot Games', 'Strategy');
INSERT INTO game VALUES ('20', 'Apex Legends', 'Respawn Entertainment', 'Action');